tomcat:
  container_name: ${SERVICE_NAME}
  restart: always
  image: tutum/jboss:as7
  net: ${DOCKER_NETWORK_NAME}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  privileged: true
  ports:
    - "8080:8080"
    - "9990:9990"
  expose:
    - "8080"
    - "9990"
  environment:
    - JBOSS_PASS="mypass"
  labels:
    - "PROJECT_NAME=${PROJECT_NAME}"
    - "ENVIRONMENT_NAME=${ENVIRONMENT_NAME}"
    - "ENVIRONMENT_TYPE=jboss"
